version: 2

models:
  - name: tb_sku_gold
    description: "The gold model"
    columns:
      - name: sku
        description: "Código do sku"

      - name: nome_campanha
        description: "Nome da campanha"  

      - name: data_campanha
        description: "Data da campanha"

      - name: valor
        description: "Valor bruto do sku"
      
      - name: tipo
        description: "Tipo do sku"