name: 'main'
version: '1.0.0'
config-version: 2

profile: 'main' # Correspondente a chave em profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  main:
    bronze:
      +materialized: incremental
      +schema: bronze
      +alias: 'tb_sku_bronze'

    silver:
      +materialized: table
      +schema: silver
      +alias: 'tb_sku_silver'
    
    gold:
      +materialized: view
      +schema: gold
      +alias: 'tb_sku_gold'

seeds:
  main:
    +schema: silver
    +alias: 'tb_sku_seed'

flags:
  use_materialization_v2: true #Necessário para o incremental