main:
  outputs:
    dev:
      catalog: dbw_eastus
      schema: bronze
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
      threads: 1
  target: dev