main:
  target: dbw_prod #Ambiente de produção
  outputs:
    dbw_prod: # Documentado em: https://docs.getdbt.com/docs/core/connect-data-platform/databricks-setup
      catalog: dbw_eastus
      schema: bronze
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
      threads: 1