version: 2

models:
  - name: tb_sku_silver
    description: "Dados tratados de SKUs"
    columns:
      - name: SKU
        tests:
          - not_null:
              severity: error
          - unique:
              severity: error

      - name: VALOR
        tests:
          - test_greater_than: # Verifica se o valor é maior que 10
              value: 10
              severity: error

      - name: TIPO
        tests:
          - dbt_utils.not_accepted_values:
              values: ['-', 'N/A', 'null']
              severity: warn